### ISSUE TITLE
Mod support?

### ISSUE THREAD

**Issue by Nitess** [Septonious/Solas-Shader#10]
Hello.
Is it possible to get immersive engineering support?
Or add more glow yourself?
I tried to add ores to a **_block.properties_**, oddly enough, **_aluminum_** **_uranium_** and **_silver_** glow, but very dimly.
**_Lead_** and **_nickel_** did not want to emit light.
Also, the **_watermill_** just disappears when shaders are enabled.
Thank you for your attention.
![2022-12-09_22 17 29](https://user-images.githubusercontent.com/30369743/206780887-6e75a7f6-86cb-459f-a1a1-30b310f86da1.png)
(Top right, zinc from create. Best result.)

**Comment by Septonious** [comment]
For now Solas isn't aiming for mod compatibility, sorry
