### ISSUE TITLE
Shimmer support options deavtivates all other effects

### ISSUE THREAD

**Issue by IvorAmlug** [Septonious/Solas-Shader#12]
i realised ur shader has support for shimmer so i checked that out and installed the forge version
Now im using oculus for shaders since i have forge (for mod reasons)
Oculus-1.4.3
rubidium-0.5.4
Shimmer-0.1.14
All for the 1.18.2 running on Forge-40.1.86
I had more mods but removed them to make sure it wasnt a 3rd party messing it up. So the above are the only mods required for that issue.
Now whenever i activate the support for shimmer in the Lighting options... the whole shader just "deactivates"
![2022-12-21_23 54 09](https://user-images.githubusercontent.com/38656481/209019176-62d2ec44-55ba-471c-8d7d-1b66fcbb5b6b.png)
And with it truned off
![2022-12-21_23 54 14](https://user-images.githubusercontent.com/38656481/209019195-68375cfe-f765-4d8d-a78d-a102e48b577d.png)
I mean when i turn it on the Shimmer Lighting obviously works at cost of the shader efffects but i dont think thats the intendet effect that option should have.
While im pretty sure this mostly something on prob Oculus or Rubidiums end im mostly curious of why it happens.
Is it cause Oculus dosnt support that feature or what is it?
Anyways i can live without the custom lights from Shimmer for know
It just rly bugged my was way to good to be tru.

-Ivor

**Comment by AshtakaOOf** [comment]
I believe that Shimmer mod compatibility was removed in commit c0462a6454cde68051128549224d5b10325bc6e0
Since currently the shader can do colored lighting without this mod.
I will let @Septonious confirm this himself :)

**Comment by IvorAmlug** [comment]
Still odd that that option still there would still be neat since u can do a bit more with shimmer than what the shader can currently do.
Example: Set lighting options for any block in any colour u want.

**Comment by AshtakaOOf** [comment]
What version do you have?

**Comment by IvorAmlug** [comment]
V1.3 which is the newest at least on curse forge

**Comment by AshtakaOOf** [comment]
Yeah the 1.3 doesn't have all the cool new stuff you can download the unstable release on the github readme

**Comment by IvorAmlug** [comment]
Ah now that options gone i see

**Comment by IvorAmlug** [comment]
So did some testing with the versions found on Curseforge out off pure curiosity.
The only 2 version where that feature dosnt deactivate everything are 1.0 and 1.1.
Now i cant say the coloured lights are rly supportet either but at least it dosnt deavtivate stuff.

**Comment by Septonious** [comment]
Shimmer support became unneeded when Solas got its own colored lighting. Shimmer performs horrible in scenes with a lot of light sources, too
