### ISSUE TITLE
Issue w/ the sky in 1.4 release

### ISSUE THREAD

**Issue by Bipbip2109** [Septonious/Solas-Shader#14]
![2023-01-20_16 17 45](https://user-images.githubusercontent.com/88253359/213734029-3cf70c62-8dab-4e8a-9e21-8604dc549e0e.png)

A darker ring is always present on top of the skybox and the clouds are a bit... blurry everywhere ? Don't know if the last on is intentional but it looks better I think. Would still be good to have an option to get the old ones since they feel more like vanilla.

Also hyped for BCL global illumination return BCL N*1  BCL ON TOP

**Comment by Septonious** [comment]
that's a known issue and it will be fixed in the next release/github commit
