### ISSUE TITLE
What Minecraft version works with these shaders?

### ISSUE THREAD

**Issue by Cimlah** [Septonious/Solas-Shader#23]
What Minecraft version should I use for Solas Shader?

**Comment by enderkruemel** [comment]
look at https://modrinth.com/shader/solas-shader/versions#all-versions
![image](https://github.com/Septonious/Solas-Shader/assets/75631674/73d3afe4-251d-4c96-8ade-e8bfb2d8784f)

**Comment by Cimlah** [comment]
Question answered
