### ISSUE TITLE
all resurces glow in the dark ( iron , gold etc ) 

### ISSUE THREAD

**Issue by 8PanthersDeep** [Septonious/Solas-Shader#24]
![Base Profile Screenshot 2023 12 28 - 17 47 00 13](https://github.com/Septonious/Solas-Shader/assets/142316194/8063752c-96f9-4c08-ad2c-e5301538a17c)
Is that normal ? Is there a way to turn them off ?

**Comment by enderkruemel** [comment]
there is an way just go to:  shader options -> PBR config -> integrated PBR -> Emissive Config. there are all the options for emissive textures.

**Comment by arden-arteles** [comment]
I know this is 2 weeks late, but you can also unzip the shader, go into shader.properties, and adjust whatever you want to behave in that manner. I've done this on several modpacks to make (most) of the modded ores glow, but it stands to reason the inverse works as well.

**Comment by baconsplit** [comment]
> I know this is 2 weeks late, but you can also unzip the shader, go into shader.properties, and adjust whatever you want to behave in that manner. I've done this on several modpacks to make (most) of the modded ores glow, but it stands to reason the inverse works as well.

doesnt fit the issue but could go more in detail how to add ores from mods to also glow? I've also noticed normal ores like diamond that are nested in new blocks (like new stoneblocks) do not glow. Any fix for that?

**Comment by arden-arteles** [comment]
> > I know this is 2 weeks late, but you can also unzip the shader, go into shader.properties, and adjust whatever you want to behave in that manner. I've done this on several modpacks to make (most) of the modded ores glow, but it stands to reason the inverse works as well.
> 
> doesnt fit the issue but could go more in detail how to add ores from mods to also glow? I've also noticed normal ores like diamond that are nested in new blocks (like new stoneblocks) do not glow. Any fix for that?

I don't know exactly how off the top off my head, but the emissive ores should all be grouped together, I just did a quick search in the file for `_ore` and added stuff on there while matching the formatting.
