### ISSUE TITLE
Colored blocks stop "coloring" if I look away from the source

### ISSUE THREAD

**Issue by mijidow** [Septonious/Solas-Shader#26]
Hi! So let's say I look at a nether portal, the blocks around it will be purple colored, but if I look away from the portal but seeing the blocks around the portal those blocks won't be purple colored anymore, is this on purpose for performance reasons or is it an issue? Thank you!
![2024-03-26_14 29 42](https://github.com/Septonious/Solas-Shader/assets/165109427/6b0b70a9-85ed-4d6c-998d-6cb5210a126d)
![2024-03-26_14 29 44](https://github.com/Septonious/Solas-Shader/assets/165109427/d3941be8-b6f9-49ff-9bcd-bb729d549075)

**Comment by KoBruh** [comment]
How did you fix this issue ?

**Comment by mijidow** [comment]
> How did you fix this issue ?

I was using the previous version lol, just update to the 2.0 beta
