### ISSUE TITLE
Nether's brightness inconsistently problem

### ISSUE THREAD

**Issue by KrokusAstra** [Septonious/Solas-Shader#33]
Hi! Those shaders on god level! Great job!
I don't really understand how to change nether's brightness. I don't understand such things - there are too many different buttons and sliders in the settings
I mean look.

Overworld looks perfectly in the dark. Dark. But not do dark - i can see something.
![image](https://github.com/Septonious/Solas-Shader/assets/172990355/e5af178b-50e7-480a-9b89-65f51bb073bf)

End Dimension 500 out of 10. Best of the best!
![image](https://github.com/Septonious/Solas-Shader/assets/172990355/e351e8ed-aba9-4338-ad15-f3aab71139cd)

And then we have f nether, where i barely able seeing something except lava
![image](https://github.com/Septonious/Solas-Shader/assets/172990355/763b8406-dd12-484e-a084-93b0d301ff92)
The second i enter Nether Fortress, i see THIS (NOTHING)
![image](https://github.com/Septonious/Solas-Shader/assets/172990355/fd434b75-b2ba-4b21-b7ea-e1a3a4322ebd)

But the second i see something bright, i'm literally feel pain in my eyes cuz of brightness.
![image](https://github.com/Septonious/Solas-Shader/assets/172990355/eaa355f7-28b3-463e-8d6b-556e935279ab)

What option of shader i need to change, to make darker corners of the nether more bright, and turn down existing light? ONLY IN NETHER!

**Comment by Septonious** [comment]
fixed
