### ISSUE TITLE
Green Cloud Shadows

### ISSUE THREAD

**Issue by Drunken0Pirate** [Septonious/Solas-Shader#36]
Minecraft Version: 1.21
Shader Loader: Iris v1.7.3
Shader Version: 2.2
This report that was printed into in-game chat:
terrain_solid.fsh: terrain_solid.fsh: 0(300) : error C1503: undefined variable "shadowtex1"

Examples of clouds
![2024-08-12_18 57 49](https://github.com/user-attachments/assets/1744fac4-0d9d-41f2-b808-6600bac57c3a)
![2024-08-12_19 02 44](https://github.com/user-attachments/assets/93060c81-0311-4a79-a839-37954db205ae)

Turning off the "Colored Shadows" setting in the config
![2024-08-12_18 58 02](https://github.com/user-attachments/assets/b8ee4817-1152-4140-898d-cfc35ba141f1)
![2024-08-12_18 58 05](https://github.com/user-attachments/assets/2aa9ebd8-73d0-48c4-8cfc-81975c2737d3)
![2024-08-12_18 58 08](https://github.com/user-attachments/assets/af3ae2dc-7ee7-4a86-8ad0-9b784f92d649)
![2024-08-12_19 02 06](https://github.com/user-attachments/assets/6bcac426-af0a-4cee-91af-c423583af110)

**Comment by Drunken0Pirate** [comment]
I forgot to take a screenshot of the clouds during daytime, here's an example.
![2024-08-12_20 01 18](https://github.com/user-attachments/assets/15a4a53b-28c9-4352-9865-bc3f92140918)

**Comment by Septonious** [comment]
fixed
