### ISSUE TITLE
[Fabric - 1.20.1] Problem with (smooth) lighting from modded light sources.

### ISSUE THREAD

**Issue by CharonMMII** [Septonious/Solas-Shader#48]
The light emitting from modded light sources seems way too dim with the shader on. Rolling back to earlier versions didn't solve the problem. 

Specs:
- Arch Linux Kernel Version 6.12.4-arch-1-1
- KDE Plasma 6.2.4 on X11
- 32GB DDR4-3200 RAM (8GB allocated to instance)
- i5-10400f
- RTX 3060

MC specs:
- sodium 0.5.3
- lithium 0.11.2
- indium 1.0.27
- iris 1.6.10

General:
![Screenshot_20241217_192907](https://github.com/user-attachments/assets/bb000d27-0139-442d-9bcc-eeccd4a000c6)

First Person:
Modded light source (MStV+ - More Torch Varients):
![2024-12-17_19 29 35](https://github.com/user-attachments/assets/2b8d4604-5961-410b-91be-03766f4c4d15)

Vanilla Light source:
![2024-12-17_19 29 46](https://github.com/user-attachments/assets/7f063dfd-dbfe-4c71-83f2-d4a5296a3bae)

**Comment by Septonious** [comment]
Not a problem or a bug. Solas replaces Minecraft's lighting engine with its own. You need to add modded light sources in blocks.properties

**Comment by CharonMMII** [comment]
Doesn't fix it.
In fact: If I try any other shader like SEUS, Complementary or Kappa, it just works.

Has to be a bug/issue with Solas imo.
