### ISSUE TITLE
Outdated Screenshots in README.md

### ISSUE THREAD

**Issue by MicrolemurDev** [Septonious/Solas-Shader#6]
Solas has been through many changes and has gotten many new features but the screenshots are from what looks to be an old version. They probably should be replaced to reflect the current development status of Solas Shaders.

**Comment by AshtakaOOf** [comment]
https://github.com/Septonious/Solas-Shader/pull/8

**Comment by MicrolemurDev** [comment]
Closing this since PR #8 got merged and fixed this issue.
